name 'powershell'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures powershell'
long_description 'Installs/Configures powershell'
version '0.1.0'
